### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by vandlol** [xxao/rebrick#1]
Hey there,
you really should add a function to call the next page while getting paginated results, or maybe add an option to query all pages and return a cummulative response.

Cheers

**Comment by xxao** [comment]
Hi,
if you use the API directly it is your responsibility to handle it. If you use the  Rebrick class, you should get all the data at once - it handles pages automatically for you.

**Comment by vandlol** [comment]
well, that either can't be true, or you are not very descriptive.
i called the .lego.get_parts() function and it returned a next link within the data, but just the first page of results

**Comment by xxao** [comment]
Hi what I meant was something like this:
rb = rebrick.Rebrick(API_KEY, USER_TOKEN)
rb.get_parts(...)

This automatically accumulates all pages for you.

Otherwise there seems to be a small bug preventing use of the 'page' parameter in API calls. I will fix it. For now you have to put the whole 'next' url there instead of just the page number.

**Comment by xxao** [comment]
The 'page' parameter should be fixed. Try current source.
